name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: actions/setup-node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: yarn install
        uses: Jaid/action-npm-install@v1.2.4

      - name: zip le bazar
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'extension'
          zipFilePath: 'build/extension.zip'
