name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: actions/setup-node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn install

      - name: Lint extension
        run: yarn run extension:lint

      - name: Build extension
        run: yarn run extension:build

      - name: Upload the generated extension as an artifact
        uses: actions/upload-artifact@v1
        with:
          name: Compiled extension
          path: build/square-ci-1.0.zip
